import type { Inspection, Profile } from "./types";

export const mockProfile: Profile = {
  companyName: "Summit Home Inspections",
  phone: "(555) 123-4567",
  email: "mike@summitinspections.com",
  licenseNumber: "HI-2024-0847",
};

export const mockInspections: Inspection[] = [
  {
    id: "insp-001",
    propertyDetails: {
      address: "142 Maple Street, Austin, TX 78701",
      propertyType: "Single Family",
      yearBuilt: "1998",
      sqft: "2,450",
      bedrooms: "4",
      bathrooms: "3",
      clientName: "Sarah Johnson",
      clientEmail: "sarah.j@email.com",
    },
    items: [
      { id: "1", category: "Exterior", itemName: "Roof", rating: "Fair", notes: "Minor wear on shingles, ~5 years remaining life", photos: [] },
      { id: "2", category: "Exterior", itemName: "Siding", rating: "Good", notes: "", photos: [] },
      { id: "3", category: "Exterior", itemName: "Foundation", rating: "Good", notes: "No visible cracks", photos: [] },
      { id: "4", category: "Exterior", itemName: "Gutters", rating: "Poor", notes: "Sagging on north side, needs replacement", photos: [] },
      { id: "5", category: "Interior", itemName: "Walls/Ceilings", rating: "Good", notes: "", photos: [] },
      { id: "6", category: "Interior", itemName: "Flooring", rating: "Good", notes: "Hardwood in good condition", photos: [] },
      { id: "7", category: "Kitchen", itemName: "Countertops", rating: "Good", notes: "Granite, no damage", photos: [] },
      { id: "8", category: "Kitchen", itemName: "Appliances", rating: "Fair", notes: "Dishwasher showing age", photos: [] },
      { id: "9", category: "Electrical", itemName: "Service Panel", rating: "Good", notes: "200 amp, properly labeled", photos: [] },
      { id: "10", category: "Electrical", itemName: "GFCI", rating: "Poor", notes: "Missing GFCI in master bathroom", photos: [] },
      { id: "11", category: "Plumbing", itemName: "Water Heater", rating: "Fair", notes: "Tank water heater, 8 years old", photos: [] },
      { id: "12", category: "HVAC", itemName: "AC", rating: "Good", notes: "2020 unit, functions well", photos: [] },
    ],
    status: "completed",
    createdAt: "2026-03-25",
    shareToken: "abc123",
  },
  {
    id: "insp-002",
    propertyDetails: {
      address: "87 Oak Avenue, Austin, TX 78704",
      propertyType: "Townhouse",
      yearBuilt: "2015",
      sqft: "1,800",
      bedrooms: "3",
      bathrooms: "2",
      clientName: "David Chen",
      clientEmail: "dchen@email.com",
    },
    items: [
      { id: "20", category: "Exterior", itemName: "Roof", rating: "Good", notes: "", photos: [] },
      { id: "21", category: "Exterior", itemName: "Siding", rating: "Good", notes: "", photos: [] },
      { id: "22", category: "Interior", itemName: "Walls/Ceilings", rating: "Good", notes: "", photos: [] },
      { id: "23", category: "Kitchen", itemName: "Countertops", rating: "Good", notes: "", photos: [] },
      { id: "24", category: "Electrical", itemName: "Service Panel", rating: "Good", notes: "", photos: [] },
      { id: "25", category: "Plumbing", itemName: "Water Heater", rating: "Good", notes: "Tankless, excellent condition", photos: [] },
    ],
    status: "completed",
    createdAt: "2026-03-22",
    shareToken: "def456",
  },
  {
    id: "insp-003",
    propertyDetails: {
      address: "310 Pine Ridge Dr, Round Rock, TX 78664",
      propertyType: "Single Family",
      yearBuilt: "2005",
      sqft: "3,100",
      bedrooms: "5",
      bathrooms: "3",
      clientName: "Emily Rodriguez",
      clientEmail: "emily.r@email.com",
    },
    items: [],
    status: "in-progress",
    createdAt: "2026-03-28",
    scheduledDate: "2026-04-01",
  },
  {
    id: "insp-004",
    propertyDetails: {
      address: "45 Elm Court, Cedar Park, TX 78613",
      propertyType: "Condo",
      yearBuilt: "2019",
      sqft: "1,200",
      bedrooms: "2",
      bathrooms: "2",
      clientName: "James Wilson",
      clientEmail: "jwilson@email.com",
    },
    items: [],
    status: "draft",
    createdAt: "2026-03-29",
    scheduledDate: "2026-04-03",
  },
];
